Fixes #55: Ensure correct controller is used to render checkExport
silverstripe/silverstripe-gridfieldqueuedexport pull request #56
Opened 2021-09-21 03:16 UTC by dizzystuff

Mimics GridFieldDetailForm_ItemRequest's getTopLevelController() method to make sure we're using the right controller in the stack to render the content of checkExport, rather than the gridfield's immediate parent controller.

2021-10-18 23:48 UTC, emteknetnz requested changes
Would you be able to retarget this at `2` - sorry the default branch was previously `master` when it should have been `2` - this has been changed at our end

2021-10-19 01:33 UTC, dizzystuff commented
Done 👍

2021-10-19 01:53 UTC, emteknetnz requested changes
Seems fine, there's a few other instances in the code base where we do something similar

Just need to remove the branch alias

2021-10-19 01:53 UTC, emteknetnz commented on composer.json
> +        "branch-alias": {
Remove the branch-alias

2021-10-19 02:06 UTC, emteknetnz approved these changes
Squash merge on green

2022-01-08 22:19 UTC, dizzystuff commented
Any chance of merging this into a new release guys?

2022-01-09 07:07 UTC, merged

2022-01-09 07:30 UTC, emteknetnz commented
@dizzystuff https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/releases/tag/2.6.2

2022-01-09 21:07 UTC, dizzystuff commented
@emteknetnz terrific, thanks!