API phpunit 9 support
silverstripe/silverstripe-gridfieldqueuedexport pull request #57
Opened 2021-10-12 23:22 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10019

2021-11-01 08:44 UTC, maxime-rainville requested changes

2021-11-01 08:44 UTC, maxime-rainville commented on src/Jobs/GenerateCSVJob.php
> +    public function setUp()
I think this was updated by accident.

2021-11-01 20:50 UTC, emteknetnz commented on src/Jobs/GenerateCSVJob.php
> +    public function setUp()
Updated

2021-11-02 01:16 UTC, maxime-rainville approved these changes
LGTM

2021-11-02 01:17 UTC, merged