FIX #80 check $gridField exists before calling getConfig()
silverstripe/silverstripe-gridfieldqueuedexport pull request #81
Opened 2023-05-23 08:17 UTC by dizzystuff

Fixes #80

2023-06-07 00:09 UTC, emteknetnz requested changes
Needs the brackets to pass linting in CI

2023-06-07 00:09 UTC, emteknetnz commented on src/Extensions/UserFormUseQueuedExportExtension.php
> +        if (empty($gridField)) return;
```suggestion
        if (empty($gridField)) {
            return;
        }
```

2023-06-08 22:32 UTC, GuySartorelli approved these changes
Seems sensible. Thanks.

2023-06-08 22:32 UTC, merged

2023-06-12 01:25 UTC, dizzystuff commented
Thanks for merging this guys. Would you mind creating a tag for it when you get a moment?

2023-06-12 01:36 UTC, GuySartorelli commented
This was merged into the next minor branch, which means it will be included in the next minor release of this module. We don't currently have a date for when that will be.